#ifndef __gui__
#define __gui__

/**
   @file
   Subclass of MainWindow, which is generated by wxFormBuilder.
*/

#include "mainwindow.h"

//// end generated include

/** Implementing MainWindow */
class GUI : public MainWindow
{
 protected:
  // Handlers for MainWindow events.
  void m_button1OnButtonClick( wxCommandEvent& event );
 public:
  /** Constructor */
  GUI( wxWindow* parent = NULL);
  //// end generated class members

  void SetViewer(osgViewer::Viewer *viewer);
  void OnIdle(wxIdleEvent& event);
};

#endif // __gui__
