#ifndef __gui__
#define __gui__

/**
   @file
   Subclass of MainWindow, which is generated by wxFormBuilder.
*/

#include "mainwindow.h"

//// end generated include

#include "physics.hpp"
#include <osg/Timer>
#include <vector>

/** Implementing MainWindow */
class GUI : public MainWindow
{
 protected:
  // Handlers for MainWindow events.
  void m_button1OnButtonClick( wxCommandEvent& event );
  Physics physicsEngine;
 public:
  /** Constructor */
  GUI( wxWindow* parent = NULL);
  //// end generated class members

  void SetViewer(osgViewer::Viewer *viewer);
  void OnIdle(wxIdleEvent& event);

  osg::ElapsedTime Timer;
  std::vector<Scene> Scenes;
  Scene* CurrentScene;
};

#endif // __gui__
